---
before_commands:
    - sudo pip install iso8601 pyyaml pytz xmltodict tzlocal gitpython tabulate click future backports.csv

checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - '*/test/*'
        - 'git_app_version/_version.py'
        - 'tests/'
        - 'tests_helpers/'

tools:
    external_code_coverage:
        timeout: 600
    pylint:
        python_version: 2
        config_file: '.pylintrc'
