---
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
  - nightly
  - pypy
  - pypy3

matrix:
  allow_failures:
    - python: '3.7-dev'
    - python: 'nightly'
    - python: 'pypy'
    - python: 'pypy3'


cache: pip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc

install:
  - pip install -U pip>=8.1.2 wheel>=0.29
  - pip install versioneer
  - pip install -r requirements-dev.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install scrutinizer-ocular ; fi

script:
  - pytest --cov=git_app_version --no-cov-on-fail --cov-report term-missing --cov-report xml

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then ocular --data-file ".coverage" --config-file ".coveragerc" ; fi

before_deploy:
  # build single executable release
  - git describe --tags --always > git_app_version/version.txt
  - if [[ -n "$TRAVIS_TAG" ]]; then pyinstaller git-app-version.spec ; tar -czf git-app-version_${TRAVIS_OS_NAME}_amd64.tar.gz -C dist git-app-version ; fi

deploy:
  - provider: pypi
    user: csanquer
    password:
      secure: "b1or0y8qmycVpL6VLitYsUMdi/oZuxDc5hXr+klTbgXmudjQ+S6FzrAMgB4MfgAkY/h+fgO1NM2tm3x96Ehgu9RRuU0dWRigX+YnAziYUuC3g6XSpjfT5caFfVRzfSuOIPftSt+67ca+IWUmXZQxZRTanobbYWMAuAb2JWGn9p6LrRfM5/9QNYQHmBO1+PnXZo1PiDzwtFQbXqvAOEq+WrEn8olTyuv8dXXrbTimZAK4Z0W1ImlObPO5Unt0tNjx5npZzV8OhuVDX6V3qs7PD91Rc40WwHL48edNl4BabnUUDUQBPYh+LXYyvl00AJkle8G5YU1CceecpKN4huebu6lzP3ApG4d1jTirpFEIK86GOo7VCEF/QWSEskJXiOuhtG8LwjiGitA+v4RrhlPD7C1LObpyF8pvgCraQECVUQdr+dT+rH/YaqJuQ4VNZVsU9HeHCszu5D9P4SItbCuFv/4nw+M5z2Xggf1ojrVQonECZ4ZMvdc//g7YjhfyiT5B9h+fJvDXGf+K3GEAlmOY991j6qfb7WoAMY9nGbJuJBtUeUziZW2v7/FZtaEvaNADgyowxBGDy0s8umGtm//kqjBrUkZZ1VV5hDdqi24dqeqYHyEIkl4dPCVsm1ky/4YligAJNXFt7YYKNojQESrJelIYuFrphEWyfKwseznHJj4="

    distributions: sdist bdist_wheel
    repo: csanquer/git-app-version
    on:
      tags: true
      python: '2.7'

  - provider: releases
    api_key:
      secure: QBQdzCE05L9RO9UGL5PurWjp8YiBGmzape0ybbYTaSDIA/d6Abdk9907bbCHqIgW7fiPzpmHgHeOXZLEiX7tgtCD5d8fqg/WGQfEpVhYrhSBG4dBdDKUnSYebsjjZGHxXlVz0fOrEV37G0NKhvuxrjclrk8tzE5jIemtimqwWotdce19A0vIDVwM8bcl6dh00pLEzRVN71EYvr7Nbzz2BxVus2RIU0l+oVk/92AONnWby9yLBL+qSpPO15f6Oq7e2Z2KYorZcUN8os8P19Eg3D9A0GHG4D9nRtvylXghAjs6sS+a5IdHgsDCZtJUVPgsqq63jBzijJqlVUmxmrPEUpFYITJmKBBqs66/L1iCBScZ27LsnjmtUgZAfUNWON7Kr8IT3WNfdUEZhhK/2HxhLrYBQJaPDL0VBYIVc8UxLWeT8BBY4RTAunqrQvEay/W3UXAWfR33lB3gu16Tdk6MYe7XJpd3mWnpXQmTSWoks5+eyYrpL0tGvdL9JVRBlfPnlf9/txf3EjbPEafkIW7pMJfbdq192cFlWto4znALMUgdAYC5bJfgvHIYDUhOljsFtyn9ogX81WKxeYJMwE475Zx2oUgYsbH7WRLEp6x7fW8qAKrVqtMjgCpGwizUY8qa6sJ3AlbxAxvJMmvyn54YcuO4F0Ya/raX8qE7196QXl0=
    file: git-app-version_${TRAVIS_OS_NAME}_amd64.tar.gz
    on:
      tags: true
      python: '2.7'
      repo: csanquer/git-app-version
