---
language: python
python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"

# old python versions
matrix:
  allow_failures:
    - python: "pypy"
    - python: "pypy3"
#     - python: "2.6"
#     - python: "3.2"

cache: pip

install:
  - pip install -r dev-requirements.txt

script:
  - coverage run -m py.test

after_success:
  - coverage report -m
  - coverage html
  - coverage xml
