---
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# old python versions
matrix:
  allow_failures:
    - "2.6"
    - "3.2"
install:
  - pip install -r dev-requirements.txt
script:
  - coverage run -m py.test
after_success:
  - coverage report -m
  - coverage html
  - coverage xml
