---
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r dev-requirements.txt
script:
  - coverage run -m py.test
after_success:
  - coverage report -m
  - coverage html
  - coverage xml
